language: python
python:
  - "3.7.5"
# command to install dependencies

addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable
    
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  - python -m spacy download en
# command to run tests
script:
  - python -m pytest ./

before_script:
    - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - sudo apt-get install chromium-browser
    - sudo apt-get install -y libglib2.0-0=2.50.3-2 \
    libnss3=2:3.26.2-1.1+deb9u1 \
    libgconf-2-4=3.2.6-4+b1 \
    libfontconfig1=2.11.0-6.7+b1
    - sudo apt-get --only-upgrade install google-chrome-stable
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver
