language: python
python:
  - "3.7.5"
# command to install dependencies

addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable
    
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  - python -m spacy download en
# command to run tests
script:
  - python -m pytest ./

before_script:
    - wget https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - sudo apt-get --only-upgrade install google-chrome-stable
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver
