language: python
python:
  - "3.7.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy download en
# command to run tests
script:
  - nohup python app.py &
