language: python
python:
  - "3.7.5"
# command to install dependencies
services:
  - xvfb
addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable
    
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  - python -m spacy download en
# command to run tests
script:
  - python -m pytest ./

before_script:
    - wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb; sudo apt-get -fy install
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver
    - export DISPLAY=:99.0
    - sleep 3

